name: Python CI

on:
  push:
  pull_request:

jobs:
  lint-and-import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: python -c "import pandas, numpy; print('Deps OK')"
      - run: python -c "open('rec_engine_final.py').read(); print('Engine OK to read')"
